### ISSUE TITLE
Webapp eigen installatie aanmeldfouten

### ISSUE THREAD

**Issue by buitermark** [Nodo-Domotica/WebApp#1]
Bij het installeren van de webapp op een eigen webserver, had ik problemen met de confirmation passkey, gaf telkens aan dat die niet overeen kwam o.i.d., maar die conform de info in de database  wel degelijk correct was.
Het inlogscherm gaf alleen "signup" en "lost password" geen "username" en "password" velden.

Installatie verliep zeer simpel, en zonder foutmeldingen.

Pas nadat ik de SQL injection prevention code geheel weggemarkeerd had uit de settings.php, waren deze problemen verholpen en zag alles er 'correct' uit, alleen SQL injection prevention is natuurlijk wel wenselijk....

in settings.php 

//SQL injection prevention
$_GET = array_map("mysql_real_escape_string", $_GET);
$_REQUEST = array_map("mysql_real_escape_string", $_REQUEST);

aangepast naar
//SQL injection prevention
//$_GET = array_map("mysql_real_escape_string", $_GET);
//$_REQUEST = array_map("mysql_real_escape_string", $_REQUEST);

om e.e.a. correct werkend te krijgen.

Draait momenteel op php PHP Version 5.4.21

**Comment by degraafm76** [comment]
Probleem is opgelost. Er miste enkele files
